version: "3.7"

services:
  mysql:
    image: mysql-storage
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./:/storage_go/docker-entrypoint-initdb.d



